language: node_js
node_js:
  - '6'
before_script:
  - yarn run dist-test
script:
  - yarn lint
  - yarn run test-es6
  - yarn run test-dist
  - yarn run check-prettier
  - yarn run check-docs
  - yarn run check-tsc
  - yarn cover
after_success:
  - npm install -g coveralls
  - cat coverage/lcov.info | coveralls
