language: node_js
node_js:
  - '8'
  - '12'
  - '14'
before_script:
  - yarn run dist-test
script:
  - yarn test-ci
  - yarn cover
after_success:
  - npm install -g coveralls
  - cat coverage/lcov.info | coveralls
